" set up linters and fixers for the languages I use
let g:ale_linters = {
\   'c': ['clangtidy'],
\}

let g:ale_fixers = {
\   '*': ['remove_trailing_lines', 'trim_whitespace'],
\   'c': ['clang-format'],
\}

" get necessary project info from compile_commands.json generated by cmake
let g:ale_c_parse_compile_commands=1
